AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Cognito User Pool

Globals:
  Function:
    Timeout: 50
    MemorySize: 256
    Architectures:
      - x86_64
    Runtime: nodejs20.x
    Environment:
      Variables:
        NODE_OPTIONS: "--enable-source-maps"

Parameters:
  StackName:
    Type: String
  Auth0ClientID:
    Type: String
  Auth0ClientSecret:
    Type: String
  Auth0Issuer:
    Type: String
  Auth0AuthorizeEndpoint:
    Type: String
  Auth0TokenEndpoint:
    Type: String

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UsernameAttributes:
        - email
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPool
      Domain: !Ref StackName

  UserPoolIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: "Auth0"
      ProviderType: "OIDC"
      ProviderDetails:
        oidc_issuer: !Ref Auth0Issuer
        authorize_scopes: "openid profile email"
        attributes_request_method: "GET"
        client_id: !Ref Auth0ClientID
        client_secret: !Ref Auth0ClientSecret
        attributes_url: https://dev-mhg8l3pi2hxgvvnt.uk.auth0.com/userinfo
        #authorize_url: https://dev-mhg8l3pi2hxgvvnt.uk.auth0.com/authorize
        #token_url: https://dev-mhg8l3pi2hxgvvnt.uk.auth0.com/oauth/token
        authorize_url: https://qylgtklxs0.execute-api.eu-west-2.amazonaws.com/prod/auth
        token_url: https://qylgtklxs0.execute-api.eu-west-2.amazonaws.com/prod/token
        jwks_uri: https://dev-mhg8l3pi2hxgvvnt.uk.auth0.com/.well-known/jwks.json

      AttributeMapping:
        username: "sub"
        email: "email"
        email_verified: "email_verified"
        phone_number: "phone_number"
        phone_number_verified: "phone_number_verified"
        profile: "profile"

  ClientUserPool:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - email
        - phone
        - profile
        - aws.cognito.signin.user.admin
      CallbackURLs:
        - http://localhost:3000/auth/
      LogoutURLs:
        - http://localhost:3000/
      SupportedIdentityProviders:
        - COGNITO
        - Auth0
      UserPoolId: !Ref UserPool

  Auth:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${StackName}-auth
      CodeUri: ../../packages
      Handler: auth.handler
      Role: !GetAtt AuthResources.Outputs.LambdaRoleArn
      Environment:
        Variables:
          proxy_callback_uri: https://qylgtklxs0.execute-api.eu-west-2.amazonaws.com/prod/callback
          idp_auth_uri: !Ref Auth0AuthorizeEndpoint
    Metadata:
      BuildMethod: esbuild
      guard:
        SuppressedRules:
          - LAMBDA_DLQ_CHECK
          - LAMBDA_INSIDE_VPC
          - LAMBDA_CONCURRENCY_CHECK
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        tsconfig: cognito/tsconfig.json
        packages: bundle
        EntryPoints:
          - cognito/src/auth.ts

  AuthResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: lambda_resources.yaml
      Parameters:
        StackName: !Ref StackName
        LambdaName: !Sub ${StackName}-auth
        LambdaArn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${StackName}-auth
        IncludeAdditionalPolicies: false
        LogRetentionInDays: 30
        CloudWatchKMSKeyId: !ImportValue account-resources:CloudwatchLogsKmsKeyArn
        EnableSplunk: False
        SplunkSubscriptionFilterRole: !ImportValue lambda-resources:SplunkSubscriptionFilterRole
        SplunkDeliveryStreamArn: !ImportValue lambda-resources:SplunkDeliveryStream

  Callback:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${StackName}-callback
      CodeUri: ../../packages
      Handler: callback.handler
      Role: !GetAtt CallbackResources.Outputs.LambdaRoleArn
      Environment:
        Variables:
          cognito_idp_response_uri: https://ab-clinical-tracker-amplify.auth.eu-west-2.amazoncognito.com/oauth2/idpresponse
    Metadata:
      BuildMethod: esbuild
      guard:
        SuppressedRules:
          - LAMBDA_DLQ_CHECK
          - LAMBDA_INSIDE_VPC
          - LAMBDA_CONCURRENCY_CHECK
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        tsconfig: cognito/tsconfig.json
        packages: bundle
        EntryPoints:
          - cognito/src/callback.ts

  CallbackResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: lambda_resources.yaml
      Parameters:
        StackName: !Ref StackName
        LambdaName: !Sub ${StackName}-callback
        LambdaArn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${StackName}-callback
        IncludeAdditionalPolicies: false
        LogRetentionInDays: 30
        CloudWatchKMSKeyId: !ImportValue account-resources:CloudwatchLogsKmsKeyArn
        EnableSplunk: False
        SplunkSubscriptionFilterRole: !ImportValue lambda-resources:SplunkSubscriptionFilterRole
        SplunkDeliveryStreamArn: !ImportValue lambda-resources:SplunkDeliveryStream

  Token:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${StackName}-token
      CodeUri: ../../packages
      Handler: token.handler
      Role: !GetAtt TokenResources.Outputs.LambdaRoleArn
      Environment:
        Variables:
          idp_token_path: !Ref Auth0TokenEndpoint
          ResponseUri: https://qylgtklxs0.execute-api.eu-west-2.amazonaws.com/prod/callback
    Metadata:
      BuildMethod: esbuild
      guard:
        SuppressedRules:
          - LAMBDA_DLQ_CHECK
          - LAMBDA_INSIDE_VPC
          - LAMBDA_CONCURRENCY_CHECK
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        tsconfig: cognito/tsconfig.json
        packages: bundle
        EntryPoints:
          - cognito/src/token.ts

  TokenResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: lambda_resources.yaml
      Parameters:
        StackName: !Ref StackName
        LambdaName: !Sub ${StackName}-token
        LambdaArn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${StackName}-token
        IncludeAdditionalPolicies: false
        LogRetentionInDays: 30
        CloudWatchKMSKeyId: !ImportValue account-resources:CloudwatchLogsKmsKeyArn
        EnableSplunk: False
        SplunkSubscriptionFilterRole: !ImportValue lambda-resources:SplunkSubscriptionFilterRole
        SplunkDeliveryStreamArn: !ImportValue lambda-resources:SplunkDeliveryStream

  RestApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub ${StackName}-apigw-cognito
      EndpointConfiguration:
        Types:
          - REGIONAL

  RestApiGatewayResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: api_resources.yaml
      Parameters:
        AdditionalPolicies: !Join
          - ","
          - - !GetAtt TokenResources.Outputs.ExecuteLambdaPolicyArn
            - !GetAtt CallbackResources.Outputs.ExecuteLambdaPolicyArn
            - !GetAtt AuthResources.Outputs.ExecuteLambdaPolicyArn
        ApiName: !Sub ${StackName}-apigw-cognito
        LogRetentionInDays: 30

  AuthAPIGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiGateway
      ParentId: !GetAtt RestApiGateway.RootResourceId
      PathPart: auth

  AuthMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiGateway
      ResourceId: !Ref AuthAPIGatewayResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        Credentials: !GetAtt RestApiGatewayResources.Outputs.ApiGwRoleArn
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Auth.Arn}/invocations

  CallbackAPIGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiGateway
      ParentId: !GetAtt RestApiGateway.RootResourceId
      PathPart: callback

  CallbackMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiGateway
      ResourceId: !Ref CallbackAPIGatewayResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        Credentials: !GetAtt RestApiGatewayResources.Outputs.ApiGwRoleArn
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Callback.Arn}/invocations

  TokenAPIGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiGateway
      ParentId: !GetAtt RestApiGateway.RootResourceId
      PathPart: token

  TokenMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiGateway
      ResourceId: !Ref TokenAPIGatewayResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        Credentials: !GetAtt RestApiGatewayResources.Outputs.ApiGwRoleArn
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Token.Arn}/invocations

  # *********************************************************************
  # If you add a new endpoint, then you need to change the name of this resource
  # You also need to change it in RestApiGatewayStage.Properties.DeploymentId
  # *********************************************************************
  RestApiGatewayDeploymentB:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      # see note above if you add something in here when you add a new endpoint
      - AuthMethod
      - CallbackMethod
      - TokenMethod
    Properties:
      RestApiId: !Ref RestApiGateway

  RestApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref RestApiGateway
      StageName: prod
      # See note above RestApiGatewayDeployment, if a new endpoint is added, then this resource name will need updating
      DeploymentId: !Ref RestApiGatewayDeploymentB
      TracingEnabled: true
      AccessLogSetting:
        DestinationArn: !GetAtt RestApiGatewayResources.Outputs.ApiGwAccessLogsArn
        Format: '{ "requestTime": "$context.requestTime", "apiId": "$context.apiId", "accountId": "$context.accountId", "resourcePath": "$context.resourcePath", "stage": "$context.stage", "requestId": "$context.requestId", "extendedRequestId": "$context.extendedRequestId", "status": "$context.status", "httpMethod": "$context.httpMethod", "protocol": "$context.protocol", "path": "$context.path", "responseLatency": "$context.responseLatency", "responseLength": "$context.responseLength", "domainName": "$context.domainName", "identity": { "sourceIp": "$context.identity.sourceIp", "userAgent": "$context.identity.userAgent", "clientCert":{ "subjectDN": "$context.identity.clientCert.subjectDN", "issuerDN": "$context.identity.clientCert.issuerDN", "serialNumber": "$context.identity.clientCert.serialNumber", "validityNotBefore": "$context.identity.clientCert.validity.notBefore", "validityNotAfter": "$context.identity.clientCert.validity.notAfter" }}, "integration":{ "error": "$context.integration.error", "integrationStatus": "$context.integration.integrationStatus", "latency": "$context.integration.latency", "requestId": "$context.integration.requestId", "status": "$context.integration.status" }}'

Outputs:
  UserPoolId:
    Description: ID of the created Cognito User Pool
    Value: !Ref UserPool
  UserPoolArn:
    Description: ID of the created Cognito User Pool
    Value: !GetAtt UserPool.Arn
  UserPoolClientId:
    Description: ID of the created Cognito User Pool client
    Value: !Ref ClientUserPool
