vulnerabilities:
  - id: CVE-2025-12816
    paths:
      - "package-lock.json"
    statement: downstream dependency just used in build stage
    expired_at: 2026-06-01
  - id: CVE-2025-66031
    paths:
      - "package-lock.json"
    statement: downstream dependency just used in build stage
    expired_at: 2026-06-01
  - id: CVE-2026-25128
    paths:
      - "package-lock.json"
    statement: downstream dependency of fast-xml-parser
    expired_at: 2026-06-01
  - id: CVE-2026-26278
    statement: fast-xml-parser vulnerability accepted as risk - dependency of aws-cdk/client-dynamodb
    expired_at: 2026-06-01
  - id: CVE-2026-26960
    statement: tar vulnerability accepted as risk
    expired_at: 2026-06-01
  - id: CVE-2026-26996
    paths:
      - "package-lock.json"
    statement: downstream dependency - vulnerability is not relevant - we don't allow user input for anything regex.
