vulnerabilities:
  - id: CVE-2025-12816
    paths:
      - "package-lock.json"
    statement: downstream dependency just used in build stage
    expired_at: 2026-06-01
  - id: CVE-2025-66031
    paths:
      - "package-lock.json"
    statement: downstream dependency just used in build stage
    expired_at: 2026-06-01
  - id: CVE-2026-25128
    paths:
      - "package-lock.json"
    statement: downstream dependency of fast-xml-parser
    expired_at: 2026-06-01
  # ajv vulnerabilities - bundled in ESLint and aws-cdk-lib, cannot be updated independently
  - id: GHSA-2g4f-4pwh-qvx6
    paths:
      - "package-lock.json"
    statement: ajv bundled in eslint and aws-cdk-lib - requires ESLint v6 compatibility, cannot force v8
    expired_at: 2026-06-01
  # fast-xml-parser vulnerabilities in bundled dependencies
  - id: GHSA-jmr7-xgp7-cmfj  
    paths:
      - "package-lock.json"
    statement: fast-xml-parser bundled in aws-sdk packages - fixed versions available but blocked by aws-sdk version constraints
    expired_at: 2026-06-01
  # lodash vulnerabilities in bundled fhir package
  - id: GHSA-xxjr-mmjv-4gpg
    paths:
      - "package-lock.json" 
    statement: lodash bundled in fhir package v4.12.0 - cannot update without major fhir version upgrade
    expired_at: 2026-06-01
  # aws-sdk v2 region parameter vulnerability
  - id: GHSA-j965-2qgj-vjmq
    paths:
      - "package-lock.json"
    statement: aws-sdk v2 region validation - used by aws-lambda package, requires application-level validation
    expired_at: 2026-06-01
