vulnerabilities:
  - id: CVE-2025-12816
    paths:
      - "package-lock.json"
    statement: downstream dependency just used in build stage
    expired_at: 2026-06-01
  - id: CVE-2025-66031
    paths:
      - "package-lock.json"
    statement: downstream dependency just used in build stage
    expired_at: 2026-06-01
  - id: CVE-2026-25128
    paths:
      - "package-lock.json"
    statement: downstream dependency of fast-xml-parser
    expired_at: 2026-06-01
  - id: CVE-2026-26278
    statement: fast-xml-parser vulnerability accepted as risk - dependency of aws-cdk/client-dynamodb
    expired_at: 2026-06-01
  - id: CVE-2026-26960
    statement: tar vulnerability accepted as risk
    expired_at: 2026-06-01
  - id: CVE-2026-26996
    paths:
      - "package-lock.json"
    statement: downstream dependency - vulnerability is not relevant - we don't allow user input for anything regex.
  - id: CVE-2026-27606
    paths:
      - "package-lock.json"
    statement: Vulnerability in AWS dependency accepted as risk
    expired_at: 2026-06-01
  - id: CVE-2026-27903
    paths:
      - "package-lock.json"
    statement: Vulnerability in minimatch - waiting for depencency updates
    expired_at: 2026-06-01
  - id: CVE-2026-27904
    paths:
      - "package-lock.json"
    statement: Vulnerability in minimatch - waiting for depencency updates
    expired_at: 2026-06-01
  - id: CVE-2026-29063
    statement: fixed - waiting for dependency updates
    expired_at: 2026-06-01
  - id: CVE-2026-32141
    statement: Transitive dependency vulnerability in flatted
    expired_at: 2026-06-01
  - id: CVE-2026-1526 
    statement: Transitive dependency vulnerability in undici of npm
    expired_at: 2026-06-01
  - id: CVE-2026-1528
    statement: Transitive dependency vulnerability in undici of npm
    expired_at: 2026-06-01
  - id: CVE-2026-2229
    statement: Transitive dependency vulnerability in undici of npm
    expired_at: 2026-06-01
  - id: CVE-2026-32597
    statement: Transitive dependency vulnerability in pyjwt
    expired_at: 2026-06-01
