vulnerabilities:
  - id: CVE-2025-12816
    paths:
      - "package-lock.json"
    statement: downstream dependency just used in build stage
    expired_at: 2026-06-01
  - id: CVE-2025-66031
    paths:
      - "package-lock.json"
    statement: downstream dependency just used in build stage
    expired_at: 2026-06-01
  - id: CVE-2026-25128
    paths:
      - "package-lock.json"
    statement: downstream dependency of fast-xml-parser
    expired_at: 2026-06-01
  - id: CVE-2026-26278
    statement: fast-xml-parser vulnerability accepted as risk - dependency of aws-cdk
    expired_at: 2026-06-01