process.env.REAL_IDP_TOKEN_PATH = "https://dummytoken.com/token"
process.env.oidcjwksEndpoint = "https://dummyauth.com/.well-known/jwks.json"
process.env.REAL_USER_POOL_IDP = "DummyPoolIdentityProvider"
process.env.oidcClientId = "valid_aud"
process.env.oidcIssuer = "valid_iss"
process.env.jwtPrivateKeyArn = "dummy_jwtPrivateKeyArn"
process.env.jwtKid = "jwt_kid"
