import {FRONTEND_PATHS} from "@/constants/environment"

export const PRESCRIPTION_LIST_PAGE_STRINGS = {
  PAGE_TITLE: "Prescriptions list",
  HEADING: "Prescriptions list",
  GO_BACK_LINK_TEXT: "Go back",
  RESULTS_PREFIX: "We found ",
  RESULTS_SUFFIX: " results",
  DEFAULT_BACK_LINK_TARGET: FRONTEND_PATHS.SEARCH_BY_PRESCRIPTION_ID,
  PRESCRIPTION_ID_SEARCH_TARGET: FRONTEND_PATHS.SEARCH_BY_PRESCRIPTION_ID,
  NHS_NUMBER_SEARCH_TARGET: FRONTEND_PATHS.SEARCH_BY_NHS_NUMBER,
  BASIC_DETAILS_SEARCH_TARGET: FRONTEND_PATHS.SEARCH_BY_BASIC_DETAILS
}
