AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  Clinical Prescription Tracker UI

Parameters:
  Auth0ClientID:
    Type: String
  Auth0ClientSecret:
    Type: String
  Auth0Issuer:
    Type: String
  Repository:
    Type: String
  OauthToken:
    Type: String

Resources:
  Cognito:
    Type: AWS::Serverless::Application
    Properties:
      Location: cognito/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        Auth0ClientID: !Ref Auth0ClientID
        Auth0ClientSecret: !Ref Auth0ClientSecret
        Auth0Issuer: !Ref Auth0Issuer

  Amplify:
    Type: AWS::Serverless::Application
    Properties:
      Location: amplify/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        Repository: !Ref Repository
        OauthToken: !Ref OauthToken
        CognitoUserPoolId: !GetAtt Cognito.Outputs.UserPoolId

Outputs:
  UserPoolId:
    Description: ID of the created Cognito User Pool
    Value: !GetAtt Cognito.Outputs.UserPoolId
