AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  Clinical Prescription Tracker UI

Parameters:
  PrimaryOIDCClientID:
    Type: String
  PrimaryOIDClientSecret:
    Type: String
  PrimaryOIDCIssuer:
    Type: String
  PrimaryOIDCAuthorizeEndpoint:
    Type: String
  PrimaryOIDCTokenEndpoint:
    Type: String
  PrimaryOIDCUserInfoEndpoint:
    Type: String
  PrimaryOIDCJWKSEndpoint:
    Type: String

Resources:
  Cognito:
    Type: AWS::Serverless::Application
    Properties:
      Location: cognito/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        PrimaryOIDCClientID: !Ref PrimaryOIDCClientID
        PrimaryOIDClientSecret: !Ref PrimaryOIDClientSecret
        PrimaryOIDCIssuer: !Ref PrimaryOIDCIssuer
        PrimaryOIDCAuthorizeEndpoint: !Ref PrimaryOIDCAuthorizeEndpoint
        PrimaryOIDCTokenEndpoint: !Ref PrimaryOIDCTokenEndpoint
        PrimaryOIDCUserInfoEndpoint: !Ref PrimaryOIDCUserInfoEndpoint
        PrimaryOIDCJWKSEndpoint: !Ref PrimaryOIDCJWKSEndpoint
        TokenMappingTableName: !GetAtt Tables.Outputs.TokenMappingTableName

  Functions:
    Type: AWS::Serverless::Application
    Properties:
      Location: functions/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        VersionNumber: "foo"
        CommitId: "bar"
        TokenMappingTableName: !GetAtt Tables.Outputs.TokenMappingTableName

  Apis:
    Type: AWS::Serverless::Application
    Properties:
      Location: apis/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        StatusFunctionName: !GetAtt Functions.Outputs.StatusFunctionName
        StatusFunctionArn: !GetAtt Functions.Outputs.StatusFunctionArn
        UserPoolArn: !GetAtt Cognito.Outputs.UserPoolArn

  Tables:
    Type: AWS::Serverless::Application
    Properties:
      Location: tables/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName

Outputs:
  PrimaryUserPoolId:
    Description: ID of the created primary Cognito User Pool
    Value: !GetAtt Cognito.Outputs.UserPoolId
    Export:
      Name: !Sub ${AWS::StackName}:Cognito:PrimaryUserPoolId
  PrimaryUserPoolClientId:
    Description: ID of the created primary Cognito User Pool client
    Value: !GetAtt Cognito.Outputs.UserPoolClientId
    Export:
      Name: !Sub ${AWS::StackName}:Cognito:PrimaryUserPoolClientId
  HostedLoginDomain:
    Description: ID of the created primary Cognito User Pool client
    Value: !GetAtt Cognito.Outputs.HostedLoginDomain
    Export:
      Name: !Sub ${AWS::StackName}:Cognito:HostedLoginDomain
