AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  Clinical Prescription Tracker UI

Parameters:
  Auth0ClientID:
    Type: String
  Auth0ClientSecret:
    Type: String
  Auth0Issuer:
    Type: String

Resources:
  Cognito:
    Type: AWS::Serverless::Application
    Properties:
      Location: cognito/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        Auth0ClientID: !Ref Auth0ClientID
        Auth0ClientSecret: !Ref Auth0ClientSecret
        Auth0Issuer: !Ref Auth0Issuer

  Functions:
    Type: AWS::Serverless::Application
    Properties:
      Location: functions/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        VersionNumber: "foo"
        CommitId: "bar"

  Apis:
    Type: AWS::Serverless::Application
    Properties:
      Location: apis/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        StatusFunctionName: !GetAtt Functions.Outputs.StatusFunctionName
        StatusFunctionArn: !GetAtt Functions.Outputs.StatusFunctionArn
        UserPoolArn: !GetAtt Cognito.Outputs.UserPoolArn

  # Amplify:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: amplify/main.yaml
  #     Parameters:
  #       StackName: !Ref AWS::StackName
  #       Repository: !Ref Repository
  #       OauthToken: !Ref OauthToken
  #       CognitoUserPoolId: !GetAtt Cognito.Outputs.UserPoolId
  #       CognitoUserPoolClientId: !GetAtt Cognito.Outputs.UserPoolClientId
