AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  Clinical Prescription Tracker UI

Parameters:
  Auth0ClientID:
    Type: String
  Auth0ClientSecret:
    Type: String
  Auth0Issuer:
    Type: String
  Auth0AuthorizeEndpoint:
    Type: String
  Auth0TokenEndpoint:
    Type: String
  Auth0UserInfoEndpoint:
    Type: String
  Auth0JWKSEndpoint:
    Type: String

Resources:
  Cognito:
    Type: AWS::Serverless::Application
    Properties:
      Location: cognito/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        Auth0ClientID: !Ref Auth0ClientID
        Auth0ClientSecret: !Ref Auth0ClientSecret
        Auth0Issuer: !Ref Auth0Issuer
        Auth0AuthorizeEndpoint: !Ref Auth0AuthorizeEndpoint
        Auth0TokenEndpoint: !Ref Auth0TokenEndpoint
        Auth0UserInfoEndpoint: !Ref Auth0UserInfoEndpoint
        Auth0JWKSEndpoint: !Ref Auth0JWKSEndpoint
        TokenMappingTableName: !GetAtt Tables.Outputs.TokenMappingTableName

  Functions:
    Type: AWS::Serverless::Application
    Properties:
      Location: functions/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        VersionNumber: "foo"
        CommitId: "bar"
        TokenMappingTableName: !GetAtt Tables.Outputs.TokenMappingTableName

  Apis:
    Type: AWS::Serverless::Application
    Properties:
      Location: apis/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        StatusFunctionName: !GetAtt Functions.Outputs.StatusFunctionName
        StatusFunctionArn: !GetAtt Functions.Outputs.StatusFunctionArn
        UserPoolArn: !GetAtt Cognito.Outputs.UserPoolArn

  Tables:
    Type: AWS::Serverless::Application
    Properties:
      Location: tables/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName

Outputs:
  PrimaryUserPoolId:
    Description: ID of the created primary Cognito User Pool
    Value: !GetAtt Cognito.Outputs.UserPoolId
    Export:
      Name: !Sub ${AWS::StackName}:Cognito:PrimaryUserPoolId
  PrimaryUserPoolClientId:
    Description: ID of the created primary Cognito User Pool client
    Value: !GetAtt Cognito.Outputs.UserPoolClientId
    Export:
      Name: !Sub ${AWS::StackName}:Cognito:PrimaryUserPoolClientId
  HostedLoginDomain:
    Description: ID of the created primary Cognito User Pool client
    Value: !GetAtt Cognito.Outputs.HostedLoginDomain
    Export:
      Name: !Sub ${AWS::StackName}:Cognito:HostedLoginDomain
