name: update_github_pages
description: "update github pages"
inputs:
  VERSION_NUMBER:
    required: true
    description: VERSION_NUMBER
  TARGET_ENVIRONMENT:
    required: true
    description: TARGET_ENVIRONMENT
  
runs:
  using: "composite"
  steps:
      - name: Checkout gh-pages
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: gh-pages
          path: gh-pages
          persist-credentials: true # needed as we use them to update gh-pages

      - name: update release tag in github pages
        shell: bash
        run: |
          cd gh-pages
          NOW=$(date +'%Y-%m-%dT%H:%M:%S')
          echo "tag,release_datetime" > "_data/${TARGET_ENVIRONMENT}_latest.csv"
          echo "${VERSION_NUMBER},${NOW}" >> "_data/${TARGET_ENVIRONMENT}_latest.csv"
          echo "${VERSION_NUMBER},${NOW}" >> "_data/${TARGET_ENVIRONMENT}_deployments.csv"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add "_data/${TARGET_ENVIRONMENT}_latest.csv"
          git add "_data/${TARGET_ENVIRONMENT}_deployments.csv"
          git commit -m "update releases for ${TARGET_ENVIRONMENT}"
          parallel --retries 10 --delay 3 ::: "git pull --rebase && git push"
        env:
          VERSION_NUMBER: ${{ inputs.VERSION_NUMBER }}
          TARGET_ENVIRONMENT: ${{ inputs.TARGET_ENVIRONMENT }}
