name: deploy_website_content

on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        required: true
        type: string
      TARGET_ENVIRONMENT:
        required: true
        type: string
      VERSION_NUMBER:
        required: true
        type: string
      COMMIT_ID:
        required: true
        type: string
    secrets:
      CLOUD_FORMATION_DEPLOY_ROLE:
        required: true
jobs:
  deploy_website_content:
    name: "deploy website content"
    runs-on: ubuntu-latest
    environment: ${{ inputs.TARGET_ENVIRONMENT }}
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout local github actions
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
          fetch-depth: 0
          sparse-checkout: |
            .github

      - name: Configure AWS Credentials
        id: connect-aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.CLOUD_FORMATION_DEPLOY_ROLE }}
          role-session-name: prescription-clinical-tracker-ui-deploy-website
          output-credentials: true

      - name: build_artifact download
        uses: actions/download-artifact@v4
        with:
          name: build_artifact

      - name: extract build_artifact
        run: |
          mkdir -p .build
          tar -xf artifact.tar -C .build

      - name: Set Environment Variables
        id: setup-env
        run: |
          hostedLoginDomain=$(aws cloudformation list-exports --region us-east-1 --query "Exports[?Name=='${{ inputs.SERVICE_NAME }}-us-certs:fullCognitoDomain:Name'].Value" --output text)
          userPoolClientId=$(aws cloudformation list-exports --region eu-west-2 --query "Exports[?Name=='${{ inputs.SERVICE_NAME }}-stateful-resources:userPoolClient:userPoolClientId'].Value" --output text)
          userPoolId=$(aws cloudformation list-exports --region eu-west-2 --query "Exports[?Name=='${{ inputs.SERVICE_NAME }}-stateful-resources:userPool:Id'].Value" --output text)
          fullCloudfrontDomain=$(aws cloudformation list-exports --region us-east-1 --query "Exports[?Name=='${{ inputs.SERVICE_NAME }}-us-certs:fullCloudfrontDomain:Name'].Value" --output text)

          {
            echo "hostedLoginDomain=${hostedLoginDomain}"
            echo "userPoolClientId=${userPoolClientId}"
            echo "userPoolId=${userPoolId}"
            echo "fullCloudfrontDomain=${fullCloudfrontDomain}"
          } >> "$GITHUB_ENV"
  
      - name: build react app
        run: |
          export NEXT_PUBLIC_hostedLoginDomain=${hostedLoginDomain}
          export NEXT_PUBLIC_userPoolClientId=${userPoolClientId}
          export NEXT_PUBLIC_userPoolId=${userPoolId}
          export NEXT_PUBLIC_redirectSignIn="https://${fullCloudfrontDomain}/site/selectyourrole.html"
          export NEXT_PUBLIC_redirectSignOut="https://${fullCloudfrontDomain}/site/logout.html"
          export NEXT_PUBLIC_COMMIT_ID=${{ inputs.COMMIT_ID }}

          cd .build
          make react-build

      - name: build auth_demo react app (temp step for testing)
        run: |
          export REACT_APP_hostedLoginDomain=${hostedLoginDomain}
          export REACT_APP_userPoolClientId=${userPoolClientId}
          export REACT_APP_userPoolId=${userPoolId}
          export REACT_APP_redirectSignIn="https://${fullCloudfrontDomain}/auth_demo/"

          cd .build
          make auth_demo_build

      - name: deploy website
        run: |
          staticBucketName=$(aws cloudformation list-exports --query "Exports[?Name=='${{ inputs.SERVICE_NAME }}-stateful-resources:StaticContentBucket:Name'].Value" --output text)
          aws s3 cp ".build/packages/staticContent/404.html" "s3://${staticBucketName}/404.html"
          aws s3 cp ".build/packages/staticContent/500.html" "s3://${staticBucketName}/500.html"
          aws s3 cp ".build/packages/staticContent/jwks/dev/jwks.json" "s3://${staticBucketName}/jwks.json"
          aws s3 cp --recursive ".build/packages/cpt-ui/out/" "s3://${staticBucketName}/${{ inputs.VERSION_NUMBER }}/"

      - name: deploy auth_demo website (temp for testing)
        run: |
          staticBucketName=$(aws cloudformation list-exports --query "Exports[?Name=='${{ inputs.SERVICE_NAME }}-stateful-resources:StaticContentBucket:Name'].Value" --output text)
          aws s3 cp --recursive ".build/packages/auth_demo/build/" "s3://${staticBucketName}/auth_demo/"
