name: Link Dev Website
on:
  pull_request:
    types: [opened]
jobs:
  link-dev-website:
    runs-on: ubuntu-22.04
    steps:
      - name: Link Dev Website
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: unsplash/comment-on-pr@b5610c6125a7197eaec80072ea35ef53e1fc6035
        with:
          msg: |
            Deployed URL: https://cpt-ui-pr-${{ github.event.pull_request.number }}.dev.eps.national.nhs.uk/site
