name: quality checks

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  quality_checks:
    uses: NHSDigital/eps-workflow-quality-checks/.github/workflows/quality-checks.yml@add_cdk
    with:
      node_version: '20'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
