name: quality checks

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  quality_checks:
    uses: NHSDigital/eps-workflow-quality-checks/.github/workflows/quality-checks.yml@v1
    with:
      node_version: '20'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  cdk-syntch-checks:
    # there are some cdk specific things not in common workflow yet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
          fetch-depth: 0

      # using git commit sha for version of action to ensure we have stable version
      - name: Install asdf
        uses: asdf-vm/actions/setup@05e0d2ed97b598bfce82fd30daf324ae0c4570e6
        with:
          asdf_branch: v0.14.1

      - name: Cache asdf
        uses: actions/cache@v4
        with:
          path: |
            ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            ${{ runner.os }}-asdf-

      - name: Install asdf dependencies in .tool-versions
        uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6
        with:
          asdf_branch: v0.14.1
        env:
          PYTHON_CONFIGURE_OPTS: --enable-shared 

      - name: make install
        run: |
          make install

      - name: run cdk synth
        run: make cdk-synth
  
      - name: run cfn-guard
        run: make cfn-guard

      - name: show cfn-guard output
        if: failure()
        run: find cfn_guard_output -type f -print0 | xargs -0 cat

      - uses: actions/upload-artifact@v4
        name: upload cfn_guard_output
        if: failure()
        with:
          name: cfn_guard_output
          path: cfn_guard_output
