name: release all stacks

on:
  workflow_call:
    inputs:
      BACKEND_STACK_NAME:
        required: true
        type: string
      TARGET_ENVIRONMENT:
        required: true
        type: string
      VERSION_NUMBER:
        required: true
        type: string
      COMMIT_ID:
        required: true
        type: string
      DEPLOY_SHARED_RESOURCES:
        required: true
        type: boolean
    secrets:
      CLOUD_FORMATION_DEPLOY_ROLE:
        required: true
      CDK_PULL_IMAGE_ROLE:
        required: true

jobs:
  release_shared_resources_uk:
    if: ${{ inputs.DEPLOY_SHARED_RESOURCES == true }}
    uses: ./.github/workflows/cdk_release_code.yml
    with:
      STACK_NAME: cpt-ui
      TARGET_ENVIRONMENT: ${{ inputs.TARGET_ENVIRONMENT }}
      VERSION_NUMBER: ${{ inputs.VERSION_NUMBER }}
      COMMIT_ID: ${{ inputs.COMMIT_ID }}
      CDK_APP_NAME: SharedResourcesApp_uk
      LOG_RETENTION_IN_DAYS: 30
      AWS_REGION: eu-west-2
    secrets:
      CDK_PULL_IMAGE_ROLE: ${{ secrets.CDK_PULL_IMAGE_ROLE }}
      CLOUD_FORMATION_DEPLOY_ROLE: ${{ secrets.CLOUD_FORMATION_DEPLOY_ROLE }}
  
  release_shared_resources_us:
    if: ${{ inputs.DEPLOY_SHARED_RESOURCES == true }}
    needs: [release_shared_resources_uk]
    uses: ./.github/workflows/cdk_release_code.yml
    with:
      STACK_NAME: cpt-ui
      TARGET_ENVIRONMENT: ${{ inputs.TARGET_ENVIRONMENT }}
      VERSION_NUMBER: ${{ inputs.VERSION_NUMBER }}
      COMMIT_ID: ${{ inputs.COMMIT_ID }}
      CDK_APP_NAME: SharedResourcesApp_us
      LOG_RETENTION_IN_DAYS: 30
      AWS_REGION: us-east-1
      GET_IMPORT_COMMANDS: |
        epsDomain=$(aws cloudformation list-exports --region eu-west-2 --output json | jq -r '.Exports[] | select(.Name == "eps-route53-resources:EPS-domain") | .Value' )
        epsZoneId=$(aws cloudformation list-exports --region eu-west-2 --output json | jq -r '.Exports[] | select(.Name == "eps-route53-resources:EPS-ZoneID") | .Value' )
        staticBucketARn=$(aws cloudformation list-exports --region eu-west-2 --output json | jq -r '.Exports[] | select(.Name == "cpt-ui-shared-resources:StaticContentBucket:Arn") | .Value' )
        staticContentBucketKmsKeyArn=$(aws cloudformation list-exports --region eu-west-2 --output json | jq -r '.Exports[] | select(.Name == "cpt-ui-shared-resources:staticContentBucketKmsKey:Arn") | .Value' )
        auditLoggingBucket=$(aws cloudformation list-exports --region eu-west-2 --output json | jq -r '.Exports[] | select(.Name == "account-resources:AuditLoggingBucket") | .Value' )
      JQ_VARIABLES: |
        --arg epsDomain "${epsDomain}" \
        --arg epsZoneId "${epsZoneId}" \
        --arg staticBucketARn "${staticBucketARn}" \
        --arg staticContentBucketKmsKeyArn "${staticContentBucketKmsKeyArn}" \
        --arg auditLoggingBucket "${auditLoggingBucket}" \
      JQ_REPLACEMENTS: |
        "epsDomain": $epsDomain,
        "epsZoneId": $epsZoneId,
        "staticBucketARn": $staticBucketARn,
        "staticContentBucketKmsKeyArn": $staticContentBucketKmsKeyArn,
        "auditLoggingBucket": $auditLoggingBucket,
    secrets:
      CDK_PULL_IMAGE_ROLE: ${{ secrets.CDK_PULL_IMAGE_ROLE }}
      CLOUD_FORMATION_DEPLOY_ROLE: ${{ secrets.CLOUD_FORMATION_DEPLOY_ROLE }}
  
  release_backend:
    uses: ./.github/workflows/cdk_release_code.yml
    needs: [release_shared_resources_uk, release_shared_resources_us]
    if: ${{ always() && !failure() && !cancelled() }}
    with:
      STACK_NAME: ${{ inputs.BACKEND_STACK_NAME }}
      TARGET_ENVIRONMENT: ${{ inputs.TARGET_ENVIRONMENT }}
      VERSION_NUMBER: ${{ inputs.VERSION_NUMBER }}
      COMMIT_ID: ${{ inputs.COMMIT_ID }}
      CDK_APP_NAME: BackendApp
      LOG_RETENTION_IN_DAYS: 30
      AWS_REGION: eu-west-2
    secrets:
      CDK_PULL_IMAGE_ROLE: ${{ secrets.CDK_PULL_IMAGE_ROLE }}
      CLOUD_FORMATION_DEPLOY_ROLE: ${{ secrets.CLOUD_FORMATION_DEPLOY_ROLE }}
