name: release all stacks

on:
  workflow_call:
    inputs:
      BRANCH_NAME:
        required: true
        type: string
      SERVICE_NAME:
        required: true
        type: string
      TARGET_ENVIRONMENT:
        required: true
        type: string
      VERSION_NUMBER:
        required: true
        type: string
      COMMIT_ID:
        required: true
        type: string
      useMockOidc:
        type: boolean
        default: false
      RUN_REGRESSION_TESTS:
        type: boolean
        default: true
      LOG_LEVEL:
        type: string
      JWT_KID:
        type: string
      REACT_LOG_LEVEL:
        type: string
        required: true
      LOG_RETENTION_IN_DAYS:
        type: string
        required: true
      IS_PULL_REQUEST:
        type: boolean
        required: true
      pinned_image:
        type: string
        required: true
jobs:
  release_all_code:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.TARGET_ENVIRONMENT }}
    container:
      image: ${{ inputs.pinned_image }}
      options: --user 1001:1001 --group-add 128
    defaults:
      run:
        shell: bash
    permissions:
      id-token: write
      contents: write
    steps:
      - name: copy .tool-versions
        run: |
          cp /home/vscode/.tool-versions "$HOME/.tool-versions"

      - name: build_artifact download
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: build_artifact

      - name: extract build_artifact
        run: tar -xf artifact.tar

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.CLOUD_FORMATION_DEPLOY_ROLE }}
          role-session-name: prescription-tracker-ui-deployment

      - name: check if fresh stateful stack deployment
        id: check_fresh_stateful_stack
        env:
          AWS_MAX_ATTEMPTS: 20
        run: |
          CF_LONDON_EXPORTS=$(aws cloudformation list-exports --region eu-west-2 --output json)
          RUM_APP_NAME=$(echo "$CF_LONDON_EXPORTS" | \
              jq \
              --arg EXPORT_NAME "${{ inputs.SERVICE_NAME }}-stateful-resources:rum:rumApp:Name" \
              -r '.Exports[] | select(.Name == $EXPORT_NAME) | .Value')

          FRESH_STATEFUL_STACK="false"
          if [ -z "${RUM_APP_NAME}" ]; then
            echo "RUM_APP_NAME not found - fresh stateful stack deployment"
            FRESH_STATEFUL_STACK="true"
          fi

          echo "FRESH_STATEFUL_STACK=$FRESH_STATEFUL_STACK" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Deploy US Certs Stack
        run: CDK_STACK_NAME=UsCertsStack npm run cdk-deploy --workspace packages/cdk
        shell: bash
        env: &deployment_env_vars
          CDK_APP_NAME: "MainDeploymentApp"
          CDK_CONFIG_serviceName: "${{ inputs.SERVICE_NAME }}"
          CDK_CONFIG_versionNumber: "${{ inputs.VERSION_NUMBER }}"
          CDK_CONFIG_commitId: "${{ inputs.COMMIT_ID }}"
          CDK_CONFIG_isPullRequest: "${{ inputs.IS_PULL_REQUEST }}"
          CDK_CONFIG_environment: "${{ inputs.TARGET_ENVIRONMENT }}"
          CDK_CONFIG_rumCloudwatchLogEnabled: "true"
          CDK_CONFIG_useMockOidc: "${{ inputs.useMockOidc }}"
          CDK_CONFIG_primaryOidcClientId: "${{ secrets.primaryOidcClientId }}"
          CDK_CONFIG_mockOidcClientId: "${{ secrets.mockOidcClientId }}"
          CDK_CONFIG_apigeeApiKey: "${{ secrets.apigeeApiKey }}"
          CDK_CONFIG_apigeeApiSecret: "${{ secrets.apigeeApiSecret }}"
          CDK_CONFIG_apigeeDoHSApiKey: "${{ secrets.apigeeDoHSApiKey }}"
          CDK_CONFIG_logRetentionInDays: "${{ inputs.LOG_RETENTION_IN_DAYS }}"
          CDK_CONFIG_logLevel: "${{ inputs.LOG_LEVEL }}"
          CDK_CONFIG_reactLogLevel: "${{ inputs.REACT_LOG_LEVEL }}"
          CDK_CONFIG_jwtPrivateKey: "${{ secrets.JWT_PRIVATE_KEY }}"
          CDK_CONFIG_jwtKid: "${{ inputs.JWT_KID }}"
          CDK_CONFIG_cloudfrontOriginCustomHeader: "${{ secrets.CLOUDFRONT_ORIGIN_CUSTOM_HEADER }}"
          REQUIRE_APPROVAL: "never"
          AWS_MAX_ATTEMPTS: 20

      - name: Initial Deploy of Stateful Stack
        if: ${{ steps.check_fresh_stateful_stack.outputs.FRESH_STATEFUL_STACK == 'true' }}
        run: CDK_STACK_NAME=StatefulStack CDK_CONFIG_rumCloudwatchLogEnabled=false npm run cdk-deploy --workspace packages/cdk
        shell: bash
        env: *deployment_env_vars

      - name: Deploy Stateful Stack
        run: CDK_STACK_NAME=StatefulStack npm run cdk-deploy --workspace packages/cdk
        shell: bash
        env: *deployment_env_vars

      - name: Deploy Stateless Stack
        run: CDK_STACK_NAME=StatelessStack npm run cdk-deploy --workspace packages/cdk
        shell: bash
        env: *deployment_env_vars

      - name: update cloudfront kvs
        id: update_cloudfront_kvs
        env:
          AWS_MAX_ATTEMPTS: 20
        shell: bash
        run: |
          # shellcheck disable=SC2140
          cloudfrontDistributionId=$(aws cloudformation list-exports --region eu-west-2 --query "Exports[?Name=='"${{ inputs.SERVICE_NAME }}-stateless-resources:cloudfrontDistribution:Id"'].Value" --output text)

          # invalidate the cache
          aws cloudfront create-invalidation --distribution-id "${cloudfrontDistributionId}" --paths '/*'

  update_github_pages:
    runs-on: ubuntu-22.04
    if: ${{ always() && !failure() && !cancelled() }}
    needs: [release_all_code]
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout gh-pages
        if: ${{ inputs.IS_PULL_REQUEST == false }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: gh-pages
          path: gh-pages

      - name: update release tag in github pages
        if: ${{ inputs.IS_PULL_REQUEST == false }}
        run: |
          cd gh-pages
          NOW=$(date +'%Y-%m-%dT%H:%M:%S')
          echo "tag,release_datetime" > _data/${{ inputs.TARGET_ENVIRONMENT }}_latest.csv
          echo "${{ inputs.VERSION_NUMBER }},${NOW}" >> _data/${{ inputs.TARGET_ENVIRONMENT }}_latest.csv
          echo "${{ inputs.VERSION_NUMBER }},${NOW}" >> _data/${{ inputs.TARGET_ENVIRONMENT }}_deployments.csv
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add _data/${{ inputs.TARGET_ENVIRONMENT }}_latest.csv
          git add _data/${{ inputs.TARGET_ENVIRONMENT }}_deployments.csv
          git commit -m 'update releases for ${{ inputs.TARGET_ENVIRONMENT }}'
          parallel --retries 10 --delay 3 ::: "git pull --rebase && git push"

  regression_tests:
    name: Regression Tests
    uses: ./.github/workflows/run_regression_tests.yml
    if: ${{ always() && !failure() && !cancelled() && inputs.RUN_REGRESSION_TESTS == true }}
    needs: [release_all_code]
    with:
      BRANCH_NAME: ${{ inputs.BRANCH_NAME }}
      ENVIRONMENT: ${{ inputs.TARGET_ENVIRONMENT }}
      VERSION_NUMBER: ${{ inputs.VERSION_NUMBER }}
      pinned_image: ${{ inputs.pinned_image }}
    secrets:
      REGRESSION_TESTS_PEM: ${{ secrets.REGRESSION_TESTS_PEM }}
